### ISSUE TITLE
bug: initializeFromDb fails if no drive scores are used by agent

### ISSUE THREAD

**Issue by cnatale** [cnatale/ihtai2#30]
```
{"name":"Ihtai","hostname":"Chriss-MacBook-Pro.local","pid":10083,"level":50,"msg":"FAILURE INITIALIZING PATTERN RECOGNITION GROUP FROM DB","time":"2018-03-15T15:56:45.673Z","v":0}
{"name":"Ihtai","hostname":"Chriss-MacBook-Pro.local","pid":10083,"level":50,"error":{"isJoi":true,"name":"ValidationError","details":[{"message":"\"0\" must be a number","path":[0,"driveState",0],"type":"number.base","context":{"key":0,"label":0}}],"_object":[{"inputState":[-40,40,0,0],"actionState":[0],"driveState":[null]},{"inputState":[-20,20,0,3],"actionState":[4],"driveState":[null]},{"inputStat....
```

... goes on like above for what i think is all pattern recognizers, then logs these errors...

```{ Error: ER_DUP_KEYNAME: Duplicate key name 'id'
    at Query.Sequence._packetToError (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/Users/natale/Projects/ihtai_2.0/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/natale/Projects/ihtai_2.0/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Users/natale/Projects/ihtai_2.0/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/Users/natale/Projects/ihtai_2.0/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/Users/natale/Projects/ihtai_2.0/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.<anonymous> (/Users/natale/Projects/ihtai_2.0/node_modules/knex/lib/runner.js:193:19)
    at Runner.tryCatcher (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/natale/Projects/ihtai_2.0/node_modules/bluebird/js/release/async.js:143:10)
  code: 'ER_DUP_KEYNAME',
  errno: 1061,
  sqlMessage: 'Duplicate key name \'id\'',
  sqlState: '42000',
  index: 0,
  sql: 'alter table `pattern_-40_40_0_0_0_` add unique `id`(`next_action`, `time_period`)' }
{"name":"Ihtai","hostname":"Chriss-MacBook-Pro.local","pid":10083,"level":50,"msg":"FAILURE INITIALIZING PATTERN RECOGNITION GROUP","time":"2018-03-15T15:56:45.823Z","v":0}
{"name":"Ihtai","hostname":"Chriss-MacBook-Pro.local","pid":10083,"level":50,"msg":"Error: PatternRecognitionGroup.addPatternRecogizer(): initializeTables() failed\n            on one or more PatternRecognizer","time":"2018-03-15T15:56:45.823Z","v":0}
TypeError: Cannot read property 'resetUpdateCount' of undefined
    at PatternRecognitionGroup.splitPatternRecognizer (/Users/natale/Projects/ihtai_2.0/server/pattern-recognition/pattern-recognition-group.js:323:64)
    at /Users/natale/Projects/ihtai_2.0/server/main.js:229:27
    at Layer.handle [as handle_request] (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/layer.js:95:5)
    at /Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/natale/Projects/ihtai_2.0/node_modules/express/lib/router/index.js:275:10)
    at /Users/natale/Projects/ihtai_2.0/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/natale/Projects/ihtai_2.0/node_modules/raw-body/index.js:224:16)
    at done (/Users/natale/Projects/ihtai_2.0/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/natale/Projects/ihtai_2.0/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: PatternRecognitionGroup.getPatternRecognizer(): 
        no patternRecognizer found matching the input string pattern_-20_20_0_-1_3_
```

**Comment by cnatale** [comment]
One way around this is to always pass a zero as drive score. Did this in the ball demo and added better messaging when pattern recognizer initialization from db succeeds but the promise fails due to already existing keys or action tables. Moving to backlog.
